---
- hosts: all
  tasks:
    - name: Stat existing files at destination.
      stat: path="~/.zsh.d/plugins"
      register: debug_stat


    - debug: msg="{{ debug_stat.stat.exists }}"

    - debug: msg="{{ ansible_env.SHELL }}"
