---
- hosts: all
  vars:
    fatline_local_path: "~/.fatline"
    sbin_dir: "~/lib"
    bin_dir : "~/bin"
    lib_dir : "~/lib"
    font_dir: "~/.fonts/misc"
    projects_dir: "~/dev"


  #pre_tasks:
    #- name: clear out any dangling symlinks
      #shell: ./rmlinks.sh ~

  vars_files:
    - host_vars/{{ ansible_hostname }}.yml
    - vars/dotfiles.yml
    - vars/gruvbox_palette.yml
    - vars/zsh_plugin_list.yml

  roles:
    - { role: dotfiles, tags: [dotfiles] }
    - { role: i3wm, tags: [i3wm] }
    - { role: zsh, tags: [zsh] }
    - { role: lib, tags: [lib] }
    - { role: projects, tags: [dev, projects] }
