---
- name: write 16 color xresource file
  template: src=templates/16-colors.j2 dest=~/.Xresources.d/16-colors backup=no
  notify:
    - xrdb merge

- name: write urxvt-256-colors xresource file
  template: src=templates/urxvt-256-colors.j2 dest=~/.Xresources.d/urxvt-256-colors backup=no
  notify:
    - xrdb merge
