---
#- name: Ensure dotfiles repository is cloned locally.
  #git:
    #repo: "{{ dotfiles_repo }}"
    #dest: "{{ dotfiles_repo_local_dest }}"
    #version: "fatline"

- include: tasks/symlink.yml
- include: tasks/tmux.yml
- include: tasks/fonts.yml
