---
#- name: Ensure dotfiles repository is cloned locally.
  #git: repo="{{ dotfiles_repo }}" dest="{{ dotfiles_repo_local_dest }}" version="fatline"

#- name: write i3 config file
  #template: src=templates/i3.j2 dest=~/.i3/config backup=no
  #notify:
    #- restart i3

- include: tasks/symlink.yml
