---
- name: check for projects location
  file: path=~/projects state=directory mode=0755

- name: update projects
  git: repo={{ item.repo }} dest=~/projects/{{ item.dest }} version={{ item.version }}
  with_items:
    - { repo: "git@github.com:roosta/utils.git", dest: "utils", version: "dev"}
    - { repo: "git@github.com:roosta/LS_COLORS.git", dest: "LS_COLORS", version: "roosta"}
    - { repo: "git@github.com:roosta/colors.git", dest: "colors", version: "master" }

- name: symlink project files.
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
    - { src: "~/projects/utils", dest: "~/utils" }
    - { src: "~/projects/colors", dest: "~/colors" }
    - { src: "~/projects/LS_COLORS/LS_COLORS", dest: "~/.dircolors" }
    - { src: "~/projects/utils/chdisp-xrandr.sh", dest: "{{ bin_dir }}/chdisp" }
    - { src: "~/projects/utils/bakc.sh", dest: "{{ bin_dir }}/bakc" }
    - { src: "~/projects/utils/touchpad-toggle.sh", dest: "{{ bin_dir }}/touchpad-toggle" }
