---
- name: Stat various user paths.
  stat: path="{{ item }}"
  register: paths_info
  with_items: 
    - "{{ sbin_dir }}"
    - "{{ bin_dir }}"
    - "{{ bin_dir }}"
    - "{{ lib_dir }}"
    - "{{ font_dir }}"
    - "{{ dev_dir }}"
    - "{{ var_dir }}"
    - "{{ var_dir }}/undo"

- name: create missing paths
  file: path="{{ item.item }}" state=directory mode=0755 recurse=yes
  when: item.stat.exists == false
  with_items: "{{ paths_info.results }}"

# - name: debug paths
#   debug: msg="{{ item.item }}"
#   with_items: "{{ paths_info.results }}"
