---
- name: Check for missing parent directory
  stat: path="{{ item.parent }}"
  register: dotfiles_parent_info
  with_items: "{{ dotfiles_files }}"

- name: create missing parent directory
  file: path="{{ item.item.parent }}" state=directory mode=0755 recurse=yes
  when: item.stat.exists == false
  with_items: "{{ dotfiles_parent_info.results }}"
